server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:kkka_auth_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # Üretimde tablo yapısının sadece doğrulanması önerilir
    show-sql: false       # Üretimde kapalı olmalı, geliştirirken açabilirsin
    properties:
      hibernate:
        format_sql: true
    open-in-view: false   # Performans ve bellek yönetimi için önerilen ayar

jwt:
  secret: ${JWT_SECRET:your_secret_key_here}
  expirationMs: ${JWT_EXPIRATION_MS:3600000}

logging:
  level:
    root: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
