version: "3.8"

services:

  discovery-service:
    build: ./backend/discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - kkka-network

  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kkka_auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: gen_bank_key_111
    depends_on:
      - discovery-service
      - postgres
    networks:
      - kkka-network

  gene-upload-service:
    build: ./backend/gene-upload-service
    container_name: gene-upload-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kkka_gene_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - discovery-service
      - postgres
    networks:
      - kkka-network

  analysis-service:
    build: ./backend/analysis-service
    container_name: analysis-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kkka_analysis_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - discovery-service
      - kafka
      - postgres
    networks:
      - kkka-network

  report-service:
    build: ./backend/report-service
    container_name: report-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kkka_report_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - discovery-service
      - postgres
    networks:
      - kkka-network

  kafka-consumer-service:
    build: ./backend/kafka-consumer-service
    container_name: kafka-consumer-service
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
      - discovery-service
    networks:
      - kkka-network

  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
      - auth-service
      - gene-upload-service
      - analysis-service
      - report-service
    networks:
      - kkka-network

  notification-service:
    build: ./backend/notification-service
    container_name: notification-service
    depends_on:
      - discovery-service
    networks:
      - kkka-network

  postgres:
    image: postgres:14
    container_name: kkka-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kkka_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - kkka-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - kkka-network

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    networks:
      - kkka-network

networks:
  kkka-network:

volumes:
  pgdata:
