server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kkka_kafka_consumer_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kafka:
  bootstrap-servers: localhost:9092
  topic:
    gene-sequences: kkka.gene.sequences

logging:
  level:
    root: INFO
